package com.test.api.model;

import com.test.api.base.model.BaseHello;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Hello extends BaseHello<Hello> {
	public static final Hello dao = new Hello().dao();
}
