/*
 * Copyright 2018 Jobsz (zcq@zhucongqi.cn)
 * 
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 * 
 *   http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
*/
package com.test.api.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by jfinal-ext3, do not modify this file.
 * The jfinal-ext3's JFinalConfigExt will load this file silently.
 */
public class MYSQLTableMappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		// Composite Primary Key order: id,name
		//arp.addMapping("hello", "id,name", Hello.class);
		// Composite Primary Key order: id,name
		arp.addMapping("user", "id,name", User.class);
	}
}

