package com.test.api.model;

import com.test.api.base.model.BaseUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class User extends BaseUser<User> {
	public static final User dao = new User().dao();
	public static final String table = "user";
}
