package cn.zcq.model;

import cn.zcq.base.model.BaseZcq;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Zcq extends BaseZcq<Zcq> {
	public static final Zcq dao = new Zcq();
	public static final String table = "zcq";
}
