package cn.zcq.model;

import cn.zcq.base.model.BaseZcqCopyZz;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ZcqCopyZz extends BaseZcqCopyZz<ZcqCopyZz> {
	public static final ZcqCopyZz dao = new ZcqCopyZz();
	public static final String table = "zcq_copy_zz";
}
